import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { WithChildren } from "@/types";
import { cn } from "@/lib";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "./_components/providers";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: WithChildren) {
  return (
    <html
      lang='en'
      className={cn("h-full", "antialiased", plusJakartaSans.className)}
    >
      <body className='min-h-full flex flex-col'>
        <Providers>{children}</Providers>
        <Toaster position='top-right' />
      </body>
    </html>
  );
}
