export const checkoutOrderSummaryStyles = {
  root: "h-fit lg:sticky lg:top-6",
  card: "bg-muted/50",
  list: "gap-1",
  item: "flex-nowrap px-0 py-2",
  content: "min-w-0",
  itemTitle: "line-clamp-none break-words",
  price: "shrink-0 text-sm font-semibold text-foreground",
  separator: "my-4",
  total: "flex items-center justify-between gap-4",
  totalLabel: "text-sm text-muted-foreground",
  totalPrice: "text-lg font-semibold text-foreground",
  footer: "border-t",
  back: "w-full",
} as const;
